version: 1
default_environment: dev
project_id: 0199df13-8670-7e72-9cfa-738eb173ac34
environments:
  - name: dev
  - name: staging
  - name: prod
plugins:
  extractors:
    - name: tap-jaffle-shop
      variant: meltanolabs
      pip_url: git+https://github.com/MeltanoLabs/tap-jaffle-shop.git
      config:
        years: 1
  loaders:
    - name: target-duckdb
      variant: jwills
      pip_url: target-duckdb~=0.8
      config:
        path: ../duckdb/jaffle_shop.duckdb
  utilities:
    - name: dbt-duckdb
      variant: jwills
      pip_url: dbt-core dbt-duckdb meltano-dbt-ext~=0.3.0
      config:
        path: ../duckdb/jaffle_shop.duckdb
        project_dir: ${DBT_PROJECT_DIR} # ../dbt/jaffle_shop
        profiles_dir: ${DBT_PROFILES_DIR} # ../dbt/jaffle_shop
    - name: superset
      variant: meltano
      pip_url: >
        apache-superset==3.1.1
        flask==2.2.5
        werkzeug==2.3.3
        jinja2==3.0.1
        wtforms==2.3.3
        git+https://github.com/meltano/superset-ext.git@main
        cryptography==41.0.2
        marshmallow<4
        click==8.1.7
        typer==0.6.1
        setuptools<81
      config:
        SECRET_KEY: ${SUPERSET_SECRET_KEY}
jobs:
  # Extract and load the raw data
  - name: el
    tasks:
      - tap-jaffle-shop target-duckdb
  # Transform the raw data
  - name: t
    tasks:
      - dbt-duckdb:run
      - dbt-duckdb:test
  # Extract, Load, and Transform
  - name: elt
    tasks:
      - tap-jaffle-shop target-duckdb
      - dbt-duckdb:run
      - dbt-duckdb:test
  # Builds the ELT pipeline
  - name: elt-build
    tasks:
      - tap-jaffle-shop target-duckdb
      - dbt-duckdb:deps
      - dbt-duckdb:build
  # Generates and serves the dbt docs site
  - name: dbt-docs
    tasks:
      - dbt-duckdb:docs-generate
      - dbt-duckdb:docs-serve
